//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViveTrack.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViveTrack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pHlltBw30KWwWzSeHjM7ZmZmZqZnihmfmZmZmZmZKY6ZYowTY8wQM3PIEO99+c6es7t/99UZ1VW3WqpSSQU2oYSQb/iL4TF/jqGpXatddOcupbt06tSlc5bvolp37xHdpXPRvNlyZsudA3/ZcubP8l3pXh179ureumjn1r16dm/eMct3NXq16BjdsnLrfnW6dGiN0Xlz5SqQs3XB/C3z582bN3cOGbNCnP8mzla+dZdOrXt275etause7QSe+73/Zw3TvHvLdtG9W+du1Ul36dq6c+de3Vv0EK2a92weM0gpxWLEC9ITEvNV0xPSaQ4Qjmn+3KkI+zSEkdcAn78xEhcPH16+Wq38s0uRQ49IMIKmepv1xyTff8G7+i8FyZszAyEzk5H/5+9t8f+/PiE5h3Y9cGBKnIPHS6w/AFy0X+n5RfP1SPQjIUOL/x+/Q//H7/969r9tQWKUTSOWk4Ykrcgk2pN6JLPIIAaS+iSjSCcmkwYkvcgrWzNH8snBRJP3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string controller {
            get {
                return ResourceManager.GetString("controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pNtVdBtL0CDgYWYmJ/EoHMdhZmbmOJw4zMzMzMzMzOAwM98wx2Fm8pb/3Yc9+7r1HY3ksWSNJHd1V7cGQREESYJIvk4OAYNNjeqt23TsVKJThw6dOsakqh3ftVubTh0L5YrNFpsjK0RstjwxqUr0aN+9R9f4Qh3je3Tv2rR9TKqqPZq1b9O8Qnyfmp3axcO9c2XPnjdbfL48zfPkypUrR1Yy+Rn0//nDsWXiO3WI7961T2yl+G6tCdhP9/zfz8E17dq8dZue8TladGA7dY7v2LFH12bdiBZNuzdNvhPDMFjy4SnpECT5UY1PkAKLww05eTP4D4NgvwZhSG+48TsJQwzY+fTazcplXl5VDz5DlGFo+CHzHr/BH/hdzRkYkiu2JILstZD/Jz4U+f/7GUG+THhx4GplMgFX0yV4+OtC2JhGhTuXjykEx1jk/7oc/L8u/8++/xPY/2xTwoslkFSIh5CAQnzEBBaiIDRQEQFhQGn0PrISTEA6IKNAR6Q7MhoM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HMD {
            get {
                return ResourceManager.GetString("HMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pLp5VE9f/P97xr3PeYskpJTMGaJJ0owoVEKiRKlUiKKk0vQxJaTQR2WokIyRJCkNaEKTSH0IRaNSadTcfb3f3+9d67fuun/ctW6Pz97PxzmdqfPe++yz3z4ESRDEKPwIU/gjRkFlvmn3Hlc3A7f9+91cFadvcXT32OPmqqu+WGWxmjL8LFbRUJxu4LnvkKe7o66ro+chd7t9itM3eNrv2+Ng7Oiz2c3FEbZWV1VdpuKoqeGgoa6urqbMCs8gKTrwYiNHt/2Oh9x9Fps6euxmYD0+/D/nENi5O+zec9hRbdd+3u2Ao6urp7u9B7PL7pCdcCOO4yjh5Y1XIAjhXrb5rBhPg4gLK99MkqAGAinCA2RwlCImwsq68sr1Rr8+SmTXE+OPkzP/LEqbun0IfjfnNUGorxcQRApL/D9+/uj//1smiF97F2a2pRCZ0xctzgTXJRx6dcB1CeIf/f+jZP8f5f+x7n9/qP8tKoQa/MEU1OoEAlMnNAgOTIPQJARgmoQ2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lighthouse {
            get {
                return ResourceManager.GetString("lighthouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fJ0D0CRb026ru9hV3WPbtnHGtu15x7Y9c8a2bdu2bdu2567cc/6IP27cuGfF7nyezNxZu6ur5sP5oPk0TfvDXxLlr6Cfj0oVmzVv07ZQ29at27ZJk6Bq4w4dm7dtkydruozpMmfgr3QZs6dJUKhzq06dOzTO06Zx504dGrRKk6B854atmoeVaty9ctuWjenOmilTjoyNc2YPy541a9bMGUy5QmQ1OF2xxm1bN+7UoXu6Mo07NjPI213+XsNt0CGsWfMujTM3ah1o265xmzadOzTsaDRq0KmBNDmO45fjRUiuabKr3mEzGNAR4eXj5h1X83/v69cuIn788WtRSD68eKVssWcXIu55pEUY6Ev0Nu222LV/UrNuu1pWt4ymZSytaXdLF7v65tGjfBHHmZVr1nyar2sJO26u7I/z/eo7/0LDPY/zxUhbuPKPhN/ynU+YuW+va5HyZ3h0Y8X8GG7+CoUq3Bl8K2H+f9+fOHJq19R8N+es/B0jV9d8v2YW2GVn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tracker {
            get {
                return ResourceManager.GetString("tracker", resourceCulture);
            }
        }
    }
}
