//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViveTrack.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViveTrack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calibration {
            get {
                object obj = ResourceManager.GetObject("Calibration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pHlltBw30KWwWzSeHjM7ZmZmZqZnihmfmZmZmZmZKY6ZYowTY8wQM3PIEO99+c6es7t/99UZ1VW3WqpSSQU2oYSQb/iL4TF/jqGpXatddOcupbt06tSlc5bvolp37xHdpXPRvNlyZsudA3/ZcubP8l3pXh179ureumjn1r16dm/eMct3NXq16BjdsnLrfnW6dGiN0Xlz5SqQs3XB/C3z582bN3cOGbNCnP8mzla+dZdOrXt275etause7QSe+73/Zw3TvHvLdtG9W+du1Ul36dq6c+de3Vv0EK2a92weM0gpxWLEC9ITEvNV0xPSaQ4Qjmn+3KkI+zSEkdcAn78xEhcPH16+Wq38s0uRQ49IMIKmepv1xyTff8G7+i8FyZszAyEzk5H/5+9t8f+/PiE5h3Y9cGBKnIPHS6w/AFy0X+n5RfP1SPQjIUOL/x+/Q//H7/969r9tQWKUTSOWk4Ykrcgk2pN6JLPIIAaS+iSjSCcmkwYkvcgrWzNH8snBRJP3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string controller {
            get {
                return ResourceManager.GetString("controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pNxjmCNd9CDwMm/ZVemZ6crY6rHRY/sd2z22bdu2bdu2bdt7+r/7YZ/9uuf3pJJU+CR1z70ntyoYjmHYP4jE88RABCyqVG7RMqFd0XZt27ZLSJ+setOOnVq2S8gflzFLxmyZITJmyZk+WdEubTp36dg0f0LTLp07NmyTPlnFLo3atGxcpmmPqu1aN4V7x2XNmitL09w5G+eMi4vLlplOfAXjf544Y4mm7do27dyxR8ZyTTu1oGA92/V/v4bQsGPjFi27Ns3WpC3frn3ThIQuHRt1opo07Nww8U4cxxGJb09NhWGJj6p/lEY8CReUxEX8bw4jfvYjsAJw4dc/AjNh5ePL18qXeHFJ2/cEUwfh4fsMO4I6v+E2fwqBxWUshmE7bez/ifcF//+uY9jnMc/3XCpP750X13mPT77KT4yoVyCnbRXAsP4F/6/Tvv/r9P+s+z9B/M+SwpKCZBiN+YDBLCwANsZiKtAwDkMgHl+K3QVjsGFYW5CADcc6g/5YHqwo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HMD {
            get {
                return ResourceManager.GetString("HMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pLp5VE9f/P97xr3PeYskpJTMGaJJ0owoVEKiRKlUiKKk0vQxJaTQR2WokIyRJCkNaEKTSH0IRaNSadTcfb3f3+9d67fuun/ctW6Pz97PxzmdqfPe++yz3z4ESRDEKPwIU/gjRkFlvmn3Hlc3A7f9+91cFadvcXT32OPmqqu+WGWxmjL8LFbRUJxu4LnvkKe7o66ro+chd7t9itM3eNrv2+Ng7Oiz2c3FEbZWV1VdpuKoqeGgoa6urqbMCs8gKTrwYiNHt/2Oh9x9Fps6euxmYD0+/D/nENi5O+zec9hRbdd+3u2Ao6urp7u9B7PL7pCdcCOO4yjh5Y1XIAjhXrb5rBhPg4gLK99MkqAGAinCA2RwlCImwsq68sr1Rr8+SmTXE+OPkzP/LEqbun0IfjfnNUGorxcQRApL/D9+/uj//1smiF97F2a2pRCZ0xctzgTXJRx6dcB1CeIf/f+jZP8f5f+x7n9/qP8tKoQa/MEU1OoEAlMnNAgOTIPQJARgmoQ2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lighthouse {
            get {
                return ResourceManager.GetString("lighthouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObjController1 {
            get {
                object obj = ResourceManager.GetObject("ObjController1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObjController2 {
            get {
                object obj = ResourceManager.GetObject("ObjController2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObjHMD {
            get {
                object obj = ResourceManager.GetObject("ObjHMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObjLighthouse1 {
            get {
                object obj = ResourceManager.GetObject("ObjLighthouse1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObjLighthouse2 {
            get {
                object obj = ResourceManager.GetObject("ObjLighthouse2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObjTracker {
            get {
                object obj = ResourceManager.GetObject("ObjTracker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fJ0DtCRZ066zKlmZVW3btqd72rbtPn3atj1t27Zt27ambdt9n9g9/1r/uuuuO8/aFe8bETtyV1Zmf5gPmk/TtN/8JVH+Cvr5qFypWfM2bQu3bd26bZt0iaqFd+jYvG2bvNkzZM6QNRN/ZcicM12iwp1bdercITxvm/DOnTo0bJUuUYXOjVo1Dysd3r1K25bhdGfPkiVX5vC/coblzJ49e9ZMplwhqhqcoXh429bhnTp0z1A2vGMzg7zd5c813IYdwpo17xKetXHrQNt24W3adO7QqKPRuGGnhtLkOI5fjhcppabJrsARMxjQERHlo/N9V/N/6+vXWiO+//Zr0Ug+uHilXPGnFyLveahFGuhL8ib9trh1flCbc9fVsrtlNS1zGU27U6b41dcPH+aPPM6sUqvWk/xdS9rxc+d8lP9n3/kXGu15lD9W+iJVvif+mv984qx9e12LUiDTwxsr5sdyC1QsXPHfwbcSF/jn3Ykjp3ZNzX9zzspfsXJ3zf9zZsFd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tracker {
            get {
                return ResourceManager.GetString("tracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ViveStart {
            get {
                object obj = ResourceManager.GetObject("ViveStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
